### ISSUE TITLE
DTSTART does not have the correct time zone

### ISSUE THREAD

**Issue by jandppw** [mrburrito/reinvent-sessions#1]
`DTSTART:20191204T154500Z` should be something like `DTSTART:20191204T154500PT`

**Comment by mrburrito** [comment]
I'll take a look at it tonight! Thanks!

**Comment by mrburrito** [comment]
I think I left time zone off for convenience so I could see all my interests at the "correct" time and pick from them without playing with time zone settings in the calendar. I'll update it to put everything in PT so it shows up correctly for Vegas.

**Comment by jandppw** [comment]
Quickfix: I did a grep replace in BBEdit with good results:

find

````
DTSTART:(201912\d\dT\d{6})Z
````

with 

````
DTSTART:\1PT
````

**Comment by mrburrito** [comment]
I just updated to export in UTC which worked perfectly in Google Calendar when I switched time zones from local to America/Los Angeles.
