### ISSUE TITLE
The user_uuid is hardcoded at get_sessions.sh...

### ISSUE THREAD

**Issue by lucianorafael** [mrburrito/reinvent-sessions#10]
Hey,
The user_uuid is hardcoded at get_sessions.sh.... So when run the script is bringing the sessions of that specific hardcoded userid instead of the new user...
By the way, I've fixed it.. you can feel free to add me as contributor if you want, I can send the PR..

**Comment by mrburrito** [comment]
Good catch!!!! Thanks!
