### ISSUE TITLE
Not getting it to work

### ISSUE THREAD

**Issue by acydgod** [mrburrito/reinvent-sessions#12]
Followed the instructions, what I noticed also is there was no userUid in the user/ response, only registrantID and attendeeTypeUid.   Tried both but each resulted in empty files (no sessions or interests)

**Comment by mrburrito** [comment]
I’ll take a look and see if they changed things up.

**Comment by mrburrito** [comment]
Can you checkout the `fix-userid` branch and re-run the script without providing a `userUid`? (Just `./get_sessions.sh`)

It looks like they removed that as a query parameter.

**Comment by acydgod** [comment]
I updated (was merged) but no improvement.  Didn't pass any userid and still empty sessions and interests.

**Comment by acydgod** [comment]
I will say I may be getting the wrong cookie?  When I go to developer tools, I just use the getReservations/, look at the large Request Header cookie, find the entry starting with AWSALB and copy that excluding the trailing ';' from it.

**Comment by mrburrito** [comment]
Hmmm. Make sure you’re copying all of the cookies, not just that one. Simplest way I’ve found is to copy the request as cURL and then find the `-H ‘Cookie: <copy_all_of_this>;`. I think someone else ran into a similar problem and that was the answer. If that’s it, I’ll update the README to be clearer!

**Comment by acydgod** [comment]
okay, that worked.  I was thrown off because you said the cookie started with AWSALB and mine didn't.  I was able to generate the ics files but only when I left out any argument 'sessions | interests' .  When I passed in either argument first, I got an error like 

$ node sessions-to-ics.js sessions sessions_2023-11-22T0049.json

node:fs:754
  return binding.read(fd, buffer, offset, length, position);

I would actually just do away with the arguments tbh and just create all the ics files where you can have one for reserved and one for favorites - I imagine that's all anyone needs since including every offered session in your calendar would surely blow it up.

**Comment by tetravista** [comment]
So, I think they changed something again.  I got this to work on the Nov 23rd, 2023 EST (copied all the cookies from the agenda uri  in chrome dev tools 'as curl' and then cut the entire cookie value into the local cookie file) and I was good. Today, when I tried to refresh my ics files with my recent changes before jumping on a flight, the sessions/list curl in the shell script seemed to be getting a 401 after I refreshed the cookie file with new cookie value.  Can you have a look?

**Comment by mrburrito** [comment]
I’ll take another look if I can. I did see the AWS Events app lets you export to calendar as well, so that might be a simpler path.
